analytics: {}
color:
  brandColors:
    - '#D8C0C0'
    - '#A87828'
    - '#A07878'
    - '#B88838'
    - '#F8D080'
  brandStrength: 0
  lightness: 0
  rhythmicContrast: 1
  saturation: 0
cta: {}
layout_spectrum: 1
name: Laipple Test
opengraph: {}
purpose: {}
typography_spectrum: 0.113176
