analytics: {}
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0
  lightness: 0
  rhythmicContrast: 1
  saturation: 0
cta: {}
layout_spectrum: 1
name: Laipple Test
opengraph: {}
purpose: {}
typography_spectrum: 0.113176
