analytics: {}
color:
  brandColors:
    - '#A8A0C0'
    - '#703830'
    - '#507098'
    - '#185088'
    - '#88C0F0'
  brandStrength: 1
  lightness: 0
  rhythmicContrast: 1
  saturation: 1
cta: {}
layout_spectrum: 1
name: Laipple Test
opengraph: {}
purpose: {}
typography_spectrum: 0.113176
