analytics: {}
color:
  brandColors:
    - '#C0C0B8'
    - '#000000'
    - '#908878'
    - '#000000'
    - '#000000'
  brandStrength: 0
  lightness: 0
  rhythmicContrast: 1
  saturation: 0
cta: {}
layout_spectrum: 1
name: Laipple Test
opengraph: {}
purpose: {}
typography_spectrum: 0.113176
