analytics: {}
color:
  brandColors:
    - '#B8C0C8'
    - '#083850'
    - '#588898'
    - '#286088'
    - '#000000'
  brandStrength: 1
  lightness: 0
  rhythmicContrast: 1
  saturation: 1
cta: {}
layout_spectrum: 1
name: Laipple Test
opengraph: {}
purpose: {}
typography_spectrum: 0.113176
